@startuml
title Диаграмма интеграции приложений банка "Стандарт"

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

AddRelTag("green", $textColor="green", $lineColor="green")
AddRelTag("red", $textColor="red", $lineColor="red")
AddRelTag("blue", $textColor="blue", $lineColor="blue")
AddRelTag("orange", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())
AddRelTag("dashedLine", $lineStyle = DashedLine())

Person(client, "Клиент", "Посещает отделение")
Person(front_office_manager, "Менеджер фронт-офиса", "")
Person(deposite_manager, "Менеджер бэк-офиса по депозитам", "")
Person(credit_manager, "Менеджер бэк-офиса по кредитам", "")
Person(call_center_operator, "Оператор кол-центра", "")
Person(it, "IT отдел", "Поддержка систем")
System_Boundary(telecom, "Телеком оператор'") {
    Container(sms, "СМС-шлюз", "Интеграция с телекомом", "Оповещения клиентов")
}
System_Boundary(boundary, "Банк 'Стандарт'") {
    Container(abs, "АБС", "Delphi + Oracle", "Учет операций, бухгалтерия")
    Container(call_center, "Система колл-центра", "Java + PostgreSQL", "Обработка обращений")
    Container(site, "Сайт банка", "PHP + React", "Маркетинговая информация")
    Container(internet_bank, "Интернет-банк", "ASP.NET + MS SQL", "Платежи, дебетовые карты")
}
Rel(client, front_office_manager, "8.Обращение в банк", "1", $tags="green")
Rel(client, front_office_manager, "1.Обращение в банк", "2", $tags="red")
Rel(client, call_center_operator, "1.Уточнение условий", "1", $tags="green")
Rel(client, site, "Маркетинговая информация", "5", $tags="dashedLine")
Rel(client, internet_bank, "Просмотр счетов и платежей", "4", $tags="dashedLine")
Rel(call_center_operator, call_center, "2.Заведение обращений", "1", $tags="green")
Rel(call_center, abs, "3.Заявка", "1", $tags="green")
Rel(internet_bank, abs, "Данные о счетах и платежах", "4", $tags="dashedLine")
Rel(front_office_manager, abs, "9.Открытие депозита, загрузка документов", "1", $tags="green")
Rel(front_office_manager, abs, "4.Открытие депозита, загрузка документов", "2", $tags="red")
Rel(front_office_manager, deposite_manager, "2.Email: уточнение условий", "2", $tags="red")
Rel(deposite_manager, credit_manager, "1.Email: запрос кредитного риска", "3", $tags="orange")
Rel(credit_manager, abs, "2.Получение данных о клиенте", "3", $tags="orange")
Rel(abs, deposite_manager, "4.Заявка из кол-центра", "1", $tags="green")
Rel(deposite_manager, abs, "5.Обработка заявки", "1", $tags="green")
Rel(credit_manager, deposite_manager, "3.Email: кредитный риск клиента", "3", $tags="orange")
Rel(deposite_manager, front_office_manager, "3.Email+Excel: ставка для клиента", "2", $tags="red")
Rel_U(it, abs, "", $tags="blue")
Rel_U(it, site, "", $tags="blue")
Rel_U(it, sms, "", $tags="blue")
Rel_U(it, call_center, "", $tags="blue")
Rel_U(it, internet_bank, "", $tags="blue")
Rel(abs, sms, "6.Запрос на оповещение", "1", $tags="green")
Rel(sms, client, "7.Отправка оповещений", "1", $tags="green")

@enduml
